//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon kancolle {
            get {
                object obj = ResourceManager.GetObject("kancolle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提督業も忙しい！.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造ドック.
        /// </summary>
        public static string Monitor_ConstructionDock {
            get {
                return ResourceManager.GetString("Monitor_ConstructionDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征.
        /// </summary>
        public static string Monitor_Expeditions {
            get {
                return ResourceManager.GetString("Monitor_Expeditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊.
        /// </summary>
        public static string Monitor_Fleet {
            get {
                return ResourceManager.GetString("Monitor_Fleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊司令部.
        /// </summary>
        public static string Monitor_FleetHq {
            get {
                return ResourceManager.GetString("Monitor_FleetHq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速建造材:.
        /// </summary>
        public static string Monitor_InstantBuild {
            get {
                return ResourceManager.GetString("Monitor_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速修復材:.
        /// </summary>
        public static string Monitor_InstantRepair {
            get {
                return ResourceManager.GetString("Monitor_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保有装備:.
        /// </summary>
        public static string Monitor_NoOfEquipment {
            get {
                return ResourceManager.GetString("Monitor_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属艦娘:.
        /// </summary>
        public static string Monitor_NoOfGirls {
            get {
                return ResourceManager.GetString("Monitor_NoOfGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務.
        /// </summary>
        public static string Monitor_Quests {
            get {
                return ResourceManager.GetString("Monitor_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠ドック.
        /// </summary>
        public static string Monitor_RepairDock {
            get {
                return ResourceManager.GetString("Monitor_RepairDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string Monitor_Settings {
            get {
                return ResourceManager.GetString("Monitor_Settings", resourceCulture);
            }
        }
    }
}
